pipeline {
    agent any

    stages {
        stage('Check Environment') {
            steps {
                sh 'docker --version'
                sh 'kubectl version --client'
                sh 'kubectl get nodes'
                sh 'kubectl get pods'
            }
        }
    }
}
